pganalyze/pganalyze-docs

install/amazon_rds/01_configure_rds_instance.md, install/amazon_rds/02_create_monitoring_user.md
Executing `pganalyze-collector --config=/etc/pganalyze-collector.conf --test` I see this error message:
[ec2-user@ip-10-112-0-176 ~]$ pganalyze-collector --config=/etc/pganalyze-collector.conf --test
2018/08/06 16:16:54 I [xxx] Testing statistics collection...
2018/08/06 16:16:54 I [xxx] pg_stat_statements does not exist, trying to create extension...
2018/08/06 16:16:54 E [xxx] Error collecting pg_stat_statements
2018/08/06 16:16:54 E [xxx] Could not process database: pq: relation "public.pg_stat_statements" does not exist
I've installed `pg_stat_statements` extenstion but this extension isn't installed in public schema:
xxx=> \dx
List of installed extensions
Name        | Version |     Schema     |                        Description …
=> Create extension in public schema.

explain/insights/expensive.md
See https://github.com/pganalyze/pganalyze/issues/709
Re: the "give more complete example" suggestion--I think we should probably focus on improving this and the other cost-based insights overall first: right now, we always use estimated cost for node cost because that's the only thing we're (almost) guaranteed to always have available. We should probably rethink that and try to use these three in order instead:
* actual time
* i/o time
* estimated cost
If we do that consistently throughout our insights, I think that will make these more useful, and we can then flesh out with examples.
=> Improve expensive insight

enterprise/releases/2020-07-0.md
- Improve wording for change with server list in navigation
- Clarify wording for webserver log output change
- Remove note on gen_random_uuid() change - whilst this occurred, we
haven't removed uuid-ossp from the DB structure yet, so uuid-ossp
is still required for installation (although its not used)
=> Enterprise 2020.07.0 release note improvements

log-insights/server/S6.md
As reported by someone, the example uses the wrong `relfilenode` in reference to the log message presented. This can be confusing when trying to follow the instructions.
=> Log Event S6: Fix typo in example SQL queries

log-insights/setup/tuning-log-config-settings.md
As per [the docs][1] (also noted [here][2]), `log_checkpoints` is not available on AWS Aurora.
[1]: https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.Reference.html
[2]: https://aws.amazon.com/blogs/database/optimizing-and-tuning-queries-in-amazon-rds-postgresql-based-on-native-and-external-tools/
=> Update docs on log_checkpoints for Aurora

log-insights/setup/self-managed.md
We've seen several customer reports of the collector not picking up a
new Log Insights configuration after a reload. We should identify and
fix the underlying issue in the collector, but in the meantime, we
should change the instructions to indicate a collector restart rather
than a reload. A restart is fairly low-impact and it's worth avoiding
confusion for now.
=> Change instructions to restart collector after Log Insights setup

install/heroku_postgres/01_deploy_the_collector.mdx
The change worked in public docs but fails if there *is* an API key to
reference (e.g., in-app). This fixes the key reference.
=> Fix Heroku Button refactor

collector/packages.mdx, components/CollectorInstallInstructions.tsx, components/CollectorPkgInstallInstructions.tsx, components/RepositorySigningKey.tsx, directory.json, install/amazon_rds/04_install_collector_ec2.mdx, install/azure_database/02_install_the_collector_deb.mdx, install/azure_database/02_install_the_collector_yum.mdx, install/google_cloud_sql/02_install_the_collector_deb.mdx, install/google_cloud_sql/02_install_the_collector_yum.mdx, install/self_managed/01_guided_setup.mdx, install/self_managed/03_install_the_collector_deb.mdx, install/self_managed/03_install_the_collector_yum.mdx
This changes our documentation to use the new install script wherever
possible, moves the "manual" package install instructions to a
separate page only in the public docs and links to that page wherever
we reference the script.
Needs testing in-app and we may also want to collapse the
distro-specific collector install pages since many are now identical.
Made the change I had proposed below, so only the manual instructions
include full key information. Other pages just show the fingerprint:
---
May also want to avoid linking the key download key on the script pages,
since it may give users the idea that downloading the key is a part of
the install process:
Maybe we should just include the fingerprint here and the download only
on the new collector packages page?
=> First stab at documenting install script

install/self_managed/00_choose_setup_method.mdx
Remove the suggestion to avoid using guided setup on production
systems to encourage broader adoption.
=> Recommend guided setup for broader usage

api/queries/getQueryStats.mdx
This field causes an n+1 query which is too slow to be useful in most
situations. We should optimize, but for now, just drop the field from
the documentation.
=> Drop tableNames from GraphQL getQueryStats documentation

collector/settings.mdx
This may even justify its own docs page in the future, but for now
giving it its own section makes it easier to link to, and allows adding
some more explanation and a test query to verify whether the setting is
working as intended.
=> Collector settings: Add separate section for schema filter settings

collector/settings.mdx
These settings are handy for configuring AWS access when running in
EKS.
My descriptions are pretty vague so I'm open to improvements, but we
should document this. Should we link the actual
AssumeRoleWithWebIdentity docs [1]? Other thoughts?
[1] https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html
=> Add documentation for aws_web_identity_token_file and aws_role_arn

install/heroku_postgres/01_deploy_the_collector.mdx
The updated MDX in Gatsby v3 seems to sometimes have issues with img
tags directly in markdown. (It garbled the inline styles and did not
resolve the image source.)
Instead, wrap the image tag in a React component, which seems to
resolve this.
=> Fix Heroku install image for Gatsby v3

explain/index.mdx, explain/setup/_verify_explain_public.mdx, explain/setup/amazon_rds/_02_actually_enable.mdx, index-advisor/index.mdx, index-advisor/standalone/index.mdx, install/amazon_rds/03_setup_iam_policy.mdx, install/amazon_rds/04_install_collector.mdx, install/amazon_rds/04_install_collector_ec2.mdx, install/amazon_rds/05_configure_the_collector.mdx, install/amazon_rds/_01_public.mdx, install/azure_database/02_install_the_collector.mdx, install/azure_database/03_configure_the_collector.mdx, install/google_cloud_sql/02_install_the_collector.mdx, install/google_cloud_sql/03_configure_the_collector.mdx, install/self_managed/02_enable_pg_stat_statements.mdx, install/self_managed/03_install_the_collector.mdx, install/self_managed/04_configure_the_collector.mdx, log-insights/setup/amazon-rds/01_test_log_download.mdx, log-insights/setup/azure-database/01_set_up_managed_identity.mdx, log-insights/setup/azure-database/02_set_up_azure_event_hub.mdx, log-insights/setup/azure-database/03_stream_logs_into_event_hub.mdx, log-insights/setup/google-cloud-sql/02_configure_log_routing.mdx, log-insights/setup/heroku-postgres/03_restart_collector.mdx, log-insights/setup/self-managed/02_configure_collector.mdx
It looks like the MDX handling changed in such a way that sometimes
breaks the syntax we were using in most places for handling images:
import imgPath from '../path/to/image'
This does still work in some places, but it's not clear what details
of the MDX structure affect what works and what doesn't.
Instead, create one-off components wrapping images in these MDX files,
which reliably works around the issue.
=> Fix images after Gatsby v3 upgrade

explain/setup/amazon_rds/_01_in_app.mdx, explain/setup/amazon_rds/_02_actually_enable.mdx, explain/setup/self_managed/_01_in_app.mdx, explain/setup/self_managed/_02_actually_enable.mdx, install.mdx, install/amazon_rds/05_configure_the_collector_docker.mdx, install/amazon_rds/05_configure_the_collector_ec2.mdx, install/amazon_rds/05_configure_the_collector_ecs.mdx, install/azure_database/03_configure_the_collector_docker.mdx, install/azure_database/03_configure_the_collector_package.mdx, install/google_cloud_sql/03_configure_the_collector_docker.mdx, install/google_cloud_sql/03_configure_the_collector_package.mdx, install/heroku_postgres/01_deploy_the_collector.mdx, install/self_managed/00_choose_setup_method.mdx, install/self_managed/04_configure_the_collector_docker.mdx, install/self_managed/04_configure_the_collector_package.mdx
As part of the move to Vite.js, we need to upgrade in-app doc
rendering to @mdx-js/mdx v2, which seems to have some minor rendering
differences:
- Some top-level React elements in MDX now always appear to render as
display:block, so work around that with a wrapper element.
- The '<>' shorthand for React.Fragment is no longer recognized. This
will probably be fixed at some point, but for now, just use the long
form.
- The Postgres logo in the "select environment" overview is now very small
(possibly since this is the only cell that stacks three lines); force
dimensions similar to what we had before.
=> Make docs compatible with MDX 2

install.mdx
Some of the MDX changes in the Vite upgrade led to the explanatory
text rendering out of the box in Chrome. The CSS here is a bit
tortured, but I couldn't figure out a simple way to straighten this
out. For now, just drop the explicit image dimensions, drop the line
break (which does not make much sense in a flexbox context anyway),
and increase the negative margin to have this match current prod.
=> Fix rendering of self-managed install button in Chrome

components/PgContribPkgInstallInstructions.tsx
Ensure we show the Postgres 14 package option.
This turned out to be drastically easier than I expected, since in
most places, the instructions for Postgres 10+ are identical, and
nothing breaks that in 14.
=> Update docs for Postgres 14

components/CheckDocumentation/queries/Slowness.tsx, util/checks/index.ts
This lets us link to the index advisor when a plan supports it or to
the index check otherwise.
=> Add index recommendation URL to issue guidance URLs

components/SQL/index.tsx
We upgraded highlight.js to 10 during our Gatsby upgrade and something
broke. Since 11 appears to work with only minor changes, update the
imports to support that.
=> Upgrade to highlight.js 11 to fix errors

components/SmartAnchor.tsx
SmartAnchor has a mostly-innocuous bug right now where it will add a
bogus 'undefined' class name if the className prop is not specified or
set to 'undefined'. This is a bug in its className handling, which was
bespoke and not relying on the classNames package because it seemed
odd for docs to depend on packages without declaring its own
dependencies.
However, given classNames is present in all current consumers, and is
a fairly small and broadly useful package, rely on it instead to avoid
future bugs and improve readability.
=> Fix className handling in SmartAnchor

components/SQL/index.tsx
The highlightBlock method is deprecated and will be removed in 12
according to a console warning from the upgraded highlight.js.
Use the renamed alternative.
=> Address highlight.js 11 warning

install/amazon_rds/_01_public.mdx
Right now, these point to demo.pganalyze.com, but due to the
navigation changes from 64f2fda29f88f52e022fc27a9c7fd550063b0a6f and
follow up commits, these routes are not valid.
Since we've been de-emphasizing demo.pganalyze.com, point these to
the official Postgres docs rather than fixing the links.
=> Update RDS docs settings links to point to official docs

components/CollectorInstallInstructions.tsx, install/self_managed/01_guided_setup.mdx
The main choice that one makes here is "guided" vs "manual" setup,
and the page offered no clear way to go back to the manual setup
when exploring the guided setup option.
Additionally, there was a confusingly worded text adjacent to the install
script. Since we don't describe a way currently to run the guided setup
with a manual package install, remove that link altogether for the guided
setup page.
In passing, add an emphasis on guided setup only support Ubuntu/Debian.
=> Guided setup: Remove link to manual pkgs, instead point to manual setup

enterprise/setup/index.mdx
If one initially sets up an organization using a password-based login,
but then enables LDAP, the LDAP users will not be members of the
organization (and will not be able to create new organizations due to
Enterprise restrictions).
Include a note explaining this in the LDAP instructions.
=> Add note about DEFAULT_ORG_ROLE to LDAP instructions

install/heroku_postgres/01_deploy_the_collector.mdx
For a large or active Heroku database, a hobby dyno may not be enough.
This will show up as crashes and missing data in pganalyze, and it may
not be obvious the collector is under-resourced. We should note this
as a potential problem during onboarding.
=> Add note about collector dyno sizing on Heroku

components/MonitoringUserSetupInstructions.tsx
Right now, this is only documented in the collector README and not as
part of normal setup. We've been trying to move installation
instructions out of the README to avoid maintaining them in multiple
places and to give users platform-specific onboarding documentation
where possible.
Because the instructions are shared across four platforms, they're a
little vague, but reviewing them in situ in each of the four guides, I
think they work.
We should also change the link in the collector warning once this is
live.
=> Document get_column_stats helper

collector/settings.mdx, install/amazon_rds/05_configure_the_collector_docker.mdx, install/amazon_rds/05_configure_the_collector_ec2.mdx, install/amazon_rds/05_configure_the_collector_ecs.mdx, install/azure_database/03_configure_the_collector_docker.mdx, install/azure_database/03_configure_the_collector_package.mdx, install/google_cloud_sql/03_configure_the_collector_docker.mdx, install/google_cloud_sql/03_configure_the_collector_package.mdx, install/self_managed/04_configure_the_collector_docker.mdx, install/self_managed/04_configure_the_collector_package.mdx
Currently, we talk about the API Keys page, but it may not be obvious
how to get there.
Describe the full navigation necessary to get to the API keys page
(Settings page, API keys tab) when referencing it.
=> Clarify references to API keys in-app

accounts/sso/index.mdx
Try to make the SSO instructions more explicit, and focused on the
(presumably) common use case of migrating all users to SSO once the
feature is enabled.
=> Update SSO docs

components/MonitoringUserSetupInstructions.tsx
In two places, we're using regular expressions with backslashes, but
because these are in TypeScript backtick-quoted strings, the
backslashes are interpreted as escapes for the following
characters. Escaped characters with no special meaning render as
themselves, but this means the backslashes are stripped.
Add additional backslashes to escape the backslashes we want to keep.
=> Fix escaping in helper function documentation

directory.json, enterprise/index.mdx, enterprise/log-insights.mdx, enterprise/settings.mdx, enterprise/setup/index.mdx, enterprise/troubleshooting.mdx, index.mdx
In the past this information has been scattered across multiple pages,
making it hard to get an overview. Instead create a dedicated page, like
we have for collector settings.
In passing remove all appendixes from the VM-based setup, make instructions
a bit less AWS specific in places (be explicit about when the AWS settings
are needed), and move troubleshooting steps to the troubleshooting page.
This also cleans up the Log Insights setup page, which was mostly moved
to the object storage setup instructions and separate collector install
steps, but still needs to exist to be linked from in-app. Modify it to
avoid duplication with the other new pages added in prior commits.
Last, this removes the LDAP_ADMIN_GROUP_CN setting documentation, since
that setting has not been supported in …
=> Introduce dedicated page for Enterprise Server container settings

install/amazon_rds/03_setup_iam_policy.mdx
This is needed for the new automatic discovery of writer and two-node
cluster reader instances in the collector.
In passing move "rds:DescribeDBInstances" together with the other
RDS-specific resources, instead of listing it as requiring "*".
=> AWS IAM policy: Add "rds:DescribeDBClusters" requirement

install/amazon_rds/_01_public.mdx
There is no argument for raising track_activity_query_size in the context of pg_stat_statements these days. This is a historic artifact from the days where pgss kept a limited query text length and tied that to the track_activity_query_size setting (usually used for pg_stat_activity).
Instead, mention track_io_timing as something to adjust, as that will have a direct impact on the usefulness of pg_stat_statements data.
=> RDS docs: Replace note on track_activity_query_size with track_io_timing

accounts/sso/index.mdx, accounts/sso/okta/index.mdx, accounts/sso/saml2.mdx
Note that the panel now shows up for everyone on the Integrations tab
of the Settings page, with a note explaining why it is not available
if that's the case, so the documentation has been updated accordingly.
=> Document that SAML is generally available

install/amazon_rds/03_setup_iam_policy.mdx
We documented this as the permission applying to "db" resources but it should actually be applied to "cluster" resources. This led to IAM permission errors when actually querying an Aurora cluster.
=> AWS setup: Fix bug in IAM policy for DescribeDBClusters

install.mdx
Previously this was different between the in-app rendering and the website docs rendering, because the in-app renderer adds an implicit p tag around the panel text (such as "Self-Managed"), but the website does not. Generally this doesn't matter, but in the case of the self-managed panel it caused a styling difference on the website.
---
Before:
After:
=> Install overview: Fix styling for Self-Managed secondary title

components/CollectorPkgInstallInstructions.tsx
- Drop Ubuntu 16.04 (it's EOL)
- Add Ubuntu 22.04
- Drop Fedora 30 and 29 (they are EOL)
- Add Fedora 35 (only adding one release due to space considerations)
- Put Amazon Linux 2 in its own tab (it's a distinct distribution)
- Mention Rocky Linux and Oracle Linux along with RHEL 8
=> Update supported platforms for collector install

collector/settings.mdx
Added in pganalyze/collector#341. Documents the option under the 'Self-managed servers' section on the collector settings page.
=> Document `always_collect_system_data` field

enterprise/setup/index.mdx
This was 404ing by accident, confusing those who were trying to follow the documentation.
=> Enterprise setup docs: Add missing /docs/ prefix to link URL

install/crunchy_bridge/01_deploy_the_collector.mdx
The default steps for Crunchy can result in only the `postgres` database being tracked, so instead this PR defaults Crunchy users to track all databases to simplify setup.
https://pganalyze.slack.com/archives/C027W74E7KP/p1675439427888259
=> Include DB_ALL_NAMES=1 in Crunchy setup steps

enterprise/setup/kubernetes_amazon_eks.mdx, enterprise/setup/object-storage-s3.mdx, install/amazon_rds/03_setup_iam_policy.mdx
```
Enterprise EKS guide: Use identical IAM policy to regular RDS setup
This was using an outdated version of the policy that did not grant
access to rds:DescribeDBClusters, which is needed for the auto-discovery
of Aurora instances.
In passing, add json syntax highlighting to the regular RDS setup guide.
```
```
Enterprise Server: Remove CORS policy requirement for S3 bucket
Since we now always fetch the logs via the regular pganalyze webserver
for Enterprise Server (to make setup easier), we no longer require the
use of this CORS policy to allow the client-side to access S3 directly.
```
=> Enterprise docs: Fix RDS policy, remove CORS settings

components/CollectorSettings.tsx
This is how we typically show other config examples, as well as the example config file that's installed with the packages.
In passing, clarify that the file is located at /etc/pganalyze-collector.conf (not just "pganalyze-collector.conf") which has been a confusion for some users, and in 99% of the cases this is the correct location.
=> Collector settings: Use "=" instead of ":" to separate key values

enterprise/troubleshooting.mdx
This can be a bit hard to debug based on the logs since its not directly referencing the AWS credentials or the IMDSv2 metadata service.
=> Enterprise troubleshooting: Document IMDSv2 hop limit error

enterprise/releases/2023-03-0.mdx
We've had this as a standard note on each release that requires database migrations to be run, so continue the practice.
=> Enterprise 2023.03.0 release: Add missing note re: required migration

components/MonitoringUserSetupInstructions.tsx, install/aiven/_01_create_monitoring_user.mdx, install/azure_database/_02_create_monitoring_user.mdx, install/google_cloud_sql/_01_create_monitoring_user.mdx
- drop 9.6 instructions (since we've dropped 9.6 support)
- drop the minPostgres flag to the MonitoringUserSetupInstructions
component since instructions are now uniform
- use the pre-pg_monitor instructions for pg_stat_statements_reset
on current versions, since this is not actually included in
pg_monitor permissions
Regarding the last point, our docs implied that pg_monitor grants the
ability to call pg_stat_statements_reset(), but I'm not sure when that
would have been in effect. The role was new as of 10, losing that
ability doesn't seem to be mentioned in the 11.0, 12.0, or 13.0
release notes, and it doesn't seem to work in the 10, 14, or 15 that I
have installed locally.
=> Update monitoring user setup instructions

install/azure_database/01_configure_azure_instance.mdx
This doc will be used in-app too, so it's important not to show SignupCTA in app (otherwise it errors, also the signup CTA doesn't make sense to have in-app).
=> Show SignupCTA public only (not in-app) for Azure configuration

collector/settings.mdx, install/azure_database/04_configure_the_collector_docker.mdx, install/azure_database/04_configure_the_collector_package.mdx, log-insights/setup/azure-database/troubleshooting.mdx
This was needed for Single Server, but by now that has been deprecated for a while, and the newer Flexible Server no longer requires this.
---
In passing, also add an extra docs link for Log Insights setup troubleshooting on Azure.
=> Azure setup: Remove outdated @your_db username example

collector/settings.mdx
This has proven more universally useful than initially assumed, so officially document it as a mechanism to use INI-style configuration when running as a Docker container.
=> Collector settings: Add documentation for CONFIG_CONTENTS

components/CheckDocumentation/vacuum/InefficientIndexPhase.tsx
This was pointed out in the review for #149, but an unrelated fix
resolved the conversation and I missed it.
=> Fix docs typo

util/checks/index.ts
Also add type declarations to the default check config structure to
avoid similar problems in the future, and fix a type definition error
with a helper function.
=> Fix structure of Inefficient Index Phase default check config

components/CheckDocumentation/index_advisor/MissingIndex.tsx
Currently, we don't have anything under "Guidance" of Missing Index check in docs. This PR adds the link to Index Advisor page.
https://pganalyze.com/docs/checks/index_advisor/missing_index
https://pganalyze-we-update-doc-6cg6ik.herokuapp.com/docs/checks/index_advisor/missing_index
=> Show the link to Index Advisor doc from MissingIndexGuidance

components/CheckDocumentation/index.tsx, components/CheckDocumentation/vacuum/XminHorizon.tsx, components/CheckDocumentation/vacuum/XminHorizonBehind.tsx, util/checks/index.ts
Add a check guidance for "VACUUM: Bloat - VACUUM Blocked By Xmin Horizon" check. The below shows all 5 causes, but in app, we will only show the specific cause that triggered a check.
In the check configuration, there is a blank "hours ago" but it's just due to some browser cache problem, it's implemented okay.
=> Add VACUUM: Bloat - VACUUM Blocked By Xmin Horizon check

components/CheckDocumentation/vacuum/InsufficientVacuumFrequency.tsx
Currently, the doc https://pganalyze.com/docs/checks/vacuum/insufficient_vacuum_frequency doesn't have anything under Guidance. This PR is going to add something there.
This will depend on https://github.com/pganalyze/pganalyze-docs/pull/160 and also the PR Lukas will open shortly.
=> Update insufficient VACUUM frequency guidance in docs page side

directory.json, vacuum-advisor/bloat-in-postgres.mdx, vacuum-advisor/toc.yml
This PR adds a super basic base of VACUUM Advisor doc, and add a new page "VACUUM Advisor: Bloat in Postgres".
To avoid showing up this in the menu, don't add contents in the main ToC or page.
https://pganalyze-we-vacuum-blo-9skjjl.herokuapp.com/docs/vacuum-advisor/bloat
=> Add VACUUM Advisor doc base and Bloat page

components/CheckDocumentation/vacuum/XminHorizon.tsx
Looking at the following note from Matthias van de Meent, it is clear that the xmin horizon won't block _every_ vacuum.
https://www.postgresql.org/message-id/CAEze2WjJZZ=P_ich+=RiA51APHsNV7zi=-j-24DCPsaV43c+Ow@mail.gmail.com
We should make it clear in some place, we can start from the xmin horizon check doc.
=> Add the explanation that the xmin horizon is server wide

install/self_managed/00_choose_setup_method.mdx
In https://github.com/pganalyze/collector/pull/438 we updated host OS
requirements for the collector, but we did not update our guided setup
requirements in our instructions.
Update the docs to reflect the new requirements.
=> Update guided setup requirements in our docs

enterprise/setup/index.mdx
This has been required since v2023.08.0.
=> Enterprise setup docs: Increase minimum Postgres version to 11

enterprise/setup/object-storage-s3.mdx
There was an occurrence where someone accidentally thought these are set in the collector configuration. Given our recent standardization around always using "/etc/pganalyze.env" as the source for Docker environment settings when running in a VM, reference that here explicitly in an effort to help understand the instructions better.
In passing link to Enterprise Server container settings page when talking about the settings for static AWS credentials.
=> Enterprsie S3 object storage: Clarify where the configuration is set

index-advisor/getting-started.mdx
As reported by a user, the Unused Index check defaults to 35 days but the documentation suggested that 2 weeks was the default.
=> Update docs for default Unused Index configuration

vacuum-advisor/what-is-freezing.mdx
Per feedback from @keiko713:
- the existing wording implied that we are creating _new_ pages when freezing
- freezing no longer happens via reserved xid but via tuple header
Update the copy to address both of these issues.
=> Clarify freezing

collector/settings.mdx
Just realized that `DB_ALL_NAMES` is not documented, so adding it. It's introduced back in 2017:
https://github.com/pganalyze/collector/blob/b366c7fa7c152894758159602cb599fa2412760a/CHANGELOG.md?plain=1#L1363
=> Add description for DB_ALL_NAMES env var for collector settings

collector/settings.mdx, install/crunchy_bridge/01_deploy_the_collector.mdx
⚠️ Blocked by https://github.com/pganalyze/collector/pull/483
Starting from the collector 0.52.3, it supports `CRUNCHY_BRIDGE_API_KEY`. Update docs to mention what it is and how to specify it.
=> Add CRUNCHY_BRIDGE_API_KEY for the doc

opentelemetry/index.mdx, opentelemetry/traceparent.mdx
From the collector v0.52.3, we can pass the pganalyze `tracestate`. This PR adds the document for it.
=> Update OpenTelemetry doc to include the pganalyze tracestate

explain/setup/azure_database/_02_actually_enable.mdx
This markdown is used to render the content in app too, so using something like `![](azure_server_params_auto_explain.png)` doesn't work. You can see that it's currently not working in the following, for example:
https://staging.pganalyze.com/servers/kfip7efqrvgydlp2h7grlwvkiq/setup/explain/azure_database/02_enable_auto_explain
To fix this, use image tag instead.
=> Use image tag instead of markdown to support showing image in app

components/CheckDocumentation/index.tsx, components/CheckDocumentation/index_advisor/IndexInsights.tsx, components/CheckDocumentation/index_advisor/IndexingEngine.tsx, util/checks/index.ts
Add a Missing Indexes issue. This is like the existing Missing Index
issue, but it looks at all index recommendations on a single table
together, rather than recommending individual indexes in separate
issues.
=> Index Advisor: Missing Indexes issue docs

install/self_managed/04_configure_the_collector_docker.mdx
The in-app instructions have a conditional for Docker-based install in the `PublicLastStepLogInsightsLink` component that explains that one needs to start the container in the background after the initial test. This was missing from the public docs, causing a confusing install experience.
=> Docker install steps: Add missing instruction for public docs

components/MonitoringUserSetupInstructions.tsx, directory.json, index-advisor/getting-started.mdx, install/crunchy_bridge/01_deploy_the_collector.mdx, install/troubleshooting.mdx, install/troubleshooting/ext_stats_helper.mdx, install/troubleshooting/toc.yml
Similar to https://pganalyze.com/docs/install/troubleshooting/column_stats_helper, create a dedicated page talking about this helper function. The warning message that mentioned in the doc will be appearing in the pganalyze app in the future.
Unlike the column stats helper, missing this helper function won't cause any warnings in the collector side, due to how we collect these data. Because of that, having this doc under install/troubleshooting is a bit inappropriate, but I can't think of any other place so I think it's okay?
=> Docs for get_relation_stats_ext helper func

collector/packages.mdx, components/CollectorPkgInstallInstructions.tsx, install/self_managed/01_guided_setup.mdx
Just realized that this list is super outdated, so I wanted to update. Since there are so many options with yumyum now, the list is a bit too crowded but I think it's okay.
The list is coming from here:
https://github.com/pganalyze/collector/blob/main/packages/repo/sync_deb.sh
https://github.com/pganalyze/collector/blob/main/packages/repo/sync_rpm.sh
https://github.com/pganalyze/collector/blob/main/packages/test/Makefile
=> Update the list of collector packages

explain/setup/amazon_rds/03_review_settings.mdx, install/amazon_rds/_01_public.mdx, install/troubleshooting/rds_pg_stat_statements_shared_preload_libraries.mdx
This mainly update two pages, to match closer for in-app setup steps.
You can find the modified pages in here:
https://pganalyze.com/docs/install/amazon_rds/01_configure_rds_instance
https://pganalyze.com/docs/install/troubleshooting/rds_pg_stat_statements_shared_preload_libraries
=> Update RDS step 1 (enabling pg_stat_statements)

_install_public.mdx, index.mdx, install/01_enabling_pg_stat_statements.mdx, install/azure_database/04_configure_the_collector.mdx, install/google_cloud_sql/03_configure_the_collector.mdx, install/self_managed/02_enable_pg_stat_statements.mdx, install/self_managed/03_install_the_collector.mdx, install/self_managed/04_configure_the_collector.mdx
This PR does 3 things:
* Update getting started overview: update the "what the collector is" to match to the docs overview page
* ~Update Enabling pg_stat_statements page: this contained some old information, so updated to match modern system~
* Fix typos: "where your Postgres is running" to "where your collector is running"
=> Update getting started overview page

components/MonitoringUserSetupInstructions.tsx
Our get_relation_stats_ext helper is specified as returning a row that
starts with two text fields, but these come from the pg_stats_ext view
and are actually `name` columns (the type for Postgres identifiers).
Postgres 13 introduced an implicit name-to-text cast, so in that version
and newer versions, our helper function works fine, but on Postgres 12
it fails with
ERROR:  return type mismatch in function declared to return record
DETAIL:  Final statement returns name instead of text at column 1.
CONTEXT:  SQL function "get_relation_stats_ext"
Update the function definition to use explicit casts for the first two
columns.
=> Fix extended statistics monitoring helpers for Postgres 12

enterprise/releases/2024-04-0.mdx
Clarify how timeseries data will be dual-written until a future Enterprise release, and add missing note regarding nginx change.
=> v2024.04.0 Enterprise release notes: Revise per feedback on Slack

components/MonitoringUserSetupInstructions.tsx
The pg_monitor role already grants access to this, so the helper is
superfluous.
=> Don't generate replication helper if pg_monitor is available

directory.json, enterprise/settings.mdx, enterprise/setup/index.mdx, install.mdx, install/amazon_rds/_03_setup_iam_policy.mdx, install/amazon_rds/iam_policy.mdx, log-insights/setup/amazon-rds/01_test_log_download.mdx
Successor of https://github.com/pganalyze/pganalyze-docs/pull/243
This PR introduces a new page called "Amazon RDS and Aurora: IAM Policy" (title can be changed), to describe about the IAM policy required for the pganalyze collector.
https://pganalyze-we-iam-policy-rewlpw.herokuapp.com/docs/install/amazon_rds/iam_policy
=> Create a dedicated page for IAM policy

install/amazon_rds/04_configure_the_collector_docker.mdx, install/amazon_rds/04_configure_the_collector_ecs.mdx, install/amazon_rds/_04_setting_env_vars.mdx, install/amazon_rds/_04_setting_env_vars_multi.mdx, install/amazon_rds/_04_setting_env_vars_multi_ecs.mdx, install/amazon_rds/_04_setting_env_vars_single.mdx, install/amazon_rds/_04_setting_env_vars_single_ecs.mdx
The current description is unclear that you need to run two separate Docker container per one simple cluster (writer and reader). It almost looks like you don't need to, which is confusing.
Let's make this clear.
This part was initially added in https://github.com/pganalyze/pganalyze-docs/pull/110
=> Update how to handle Aurora cluster with Docker

components/MonitoringUserSetupInstructions.tsx, install/crunchy_bridge/01_deploy_the_collector.mdx
Currently, we prompt users to create helper functions to access column
stats and extended statistics separately, even though both of these
have to be created per-database.
Consolidate these, so users only have to iterate through their
databases once.
=> Consolidate per-database helper function instructions

install/amazon_rds/_04_setting_env_vars_multi_ecs.mdx, install/amazon_rds/_04_setting_env_vars_single_ecs.mdx
Minor improvement for the ecs documentation. If the user is not set to "1000", by default it will be the user with id 0 and this part of the collector entrypoint.sh will execute: https://github.com/pganalyze/collector/blob/main/contrib/docker-entrypoint.sh#L10-L12
This is a problem because it crashes on startup with the following error: 
```
/ $ setpriv --reuid=pganalyze --regid=pganalyze --inh-caps=-all --clear-groups
setpriv: unrecognized option: reuid=pganalyze
BusyBox v1.36.1 (2023-11-06 11:32:24 UTC) multi-call binary.
Usage: setpriv [OPTIONS] PROG ARGS
Run PROG with different privilege settings
-d,--dump               Show current capabilities
--nnp,--no-new-privs    Ignore setuid/setgid bits and file capabilities
--inh-caps CAP,CAP      Set inheritable capabilities
--ambient-caps …
```
=> docs: set user id to 1000 on the ecs task

components/MonitoringUserSetupInstructions.tsx
Column stats collection on RDS with Postgres 16 is currently failing with:
```
error collecting column statistics: pq: permission denied for attribute pg_subscription.subconninfo
```
This PR fixes that by excluding internal Postgres tables in `get_column_stats` and `get_relation_stats_ext` helper functions, since we'd later discard the data anyway.
=> Exclude internal Postgres tables from stats helper functions

images/collector_aws_architecture.svg, install/amazon_rds/00_overview.mdx
Ok let's see if people like this. I like it overall, but one big downside is that now 00_overview page is almost too long.
I can also add "Collector can be installed in a different AWS account..." part in the diagram, like a footnote, which might work better (though maybe it's easier to review as a markdown :P).
=> Add AWS architecture diagram and note for cross account

log-insights/setup/aiven/04_configure_service_integration.mdx, log-insights/setup/azure-database/05_configure_collector.mdx, log-insights/setup/crunchy-bridge/01_create_helper_function_and_test.mdx, log-insights/setup/google-cloud-sql/04_configure_collector.mdx
This has been bothering me quite a bit, let's update old links.
* Azure, Crunchy, Google => they have auto explain, so let's link to auto explain page
* Aiven => they actually don't support auto explain, so let's link to log based explain page
=> Update stale links and point to auto explain

enterprise/setup/kubernetes_amazon_eks.mdx
Since the v2024.04.0 release, we need to ensure all paths are set up correctly, not just RVM. Since the Entrypoint has been modified to allow calling it directly more easily, switch the K8S documentation to call it to initialize the environment and run rake tasks.
In passing change the use of "db:setup" (which runs the migrations) to "db:structure:load" (which loads structure.sql) + "db:seed". This matches the VM-based setup instructions.
=> Enterprise EKS setup: Use Entrypoint script, db:structure:load

install/amazon_rds/04_configure_the_collector_eks.mdx
Currently, this part is pretty hand wavy as it just says "follow your organization's security best practices and use Kubernetes secrets". With this, I mention how it actually can be used.
For the k8s secret, the key must consist of alphanumeric characters, `-`, `_` or `.`, so we should be able to use `pganalyze-collector.conf` as the key.
Reference:
https://kubernetes.io/docs/concepts/configuration/secret/#use-case-dotfiles-in-a-secret-volume
https://kubernetes.io/docs/concepts/configuration/secret/#restriction-names-data
=> Add an example of using k8s secret with EKS setup

collector/settings.mdx, components/CollectorLogTest.tsx, components/CollectorSettings.tsx, explain/setup/log_explain/02_enable_log_explain.mdx, install/aiven/05_configure_the_collector_package.mdx, install/amazon_rds/04_configure_the_collector_ec2.mdx, install/azure_database/04_configure_the_collector_package.mdx, install/google_cloud_sql/03_configure_the_collector_package.mdx, install/self_managed/04_configure_the_collector_package.mdx
The default behavior now reload config without passing `--reload` flag with successful run, so let's remove `--reload` flag to avoid confusion:
https://github.com/pganalyze/collector/blob/main/CHANGELOG.md#0500------2023-06-05
Also tweaked a bit about where to update the collector config (it should be safe to say "under the server section").
=> Remove --reload flag from the collector tests

directory.json, explain/other-nodes/limit.mdx
Looks like this got mixed up in
aa025a5e6006b944699046d09a37105d7807b067. Reviewing that commit's
EXPLAIN docs changes, I did not find any similar problems.
=> Fix EXPLAIN Limit node docs

components/SmartAnchor.tsx, install/heroku_postgres/01_deploy_the_collector.mdx
The current deployment link is outdated and links to a blank state of the "new app" view in Heroku. See before and after.
| Before  | After |
| ------------- | ------------- |
| <img width="500" alt="Screenshot 2024-08-27 at 11 57 03 AM" src="https://github.com/user-attachments/assets/72830753-4747-4794-868a-3d1bf7bdbcd8">  | <img width="500" alt="Screenshot 2024-08-27 at 11 57 26 AM" src="https://github.com/user-attachments/assets/a8dbcb20-a715-45c0-bece-17b2851e9a17">  |
=> Update Heroku deployment link

install/amazon_rds/03_install_collector_eks.mdx, install/amazon_rds/04_configure_the_collector_eks.mdx, install/amazon_rds/_03_create_iam_role_eks_pod_identity.mdx
With a new collector, now people can use Pod Identity with EKS. I double checked and confirmed that this works with a new collector.
Revive the doc that I created previously to mention the Pod Identity way.
=> Update EKS setup docs to include Pod Identity usage

components/MonitoringUserSetupInstructions.tsx
On Postgres 17, the function breaks:
```sql
select * from pganalyze.get_column_stats() limit 1;
ERROR:  return type mismatch in function declared to return pg_stats
DETAIL:  Final statement returns too few columns.
CONTEXT:  SQL function "get_column_stats" during startup
```
Note that this documentation update makes it so this function definition no longer works for previous versions of Postgres. Do we have a UI pattern to handle this, like a tabbed component that lets you switch between PG 16 and 17 versions of the function?
This error wouldn't have occurred if the function didn't `RETURNS SETOF pg_stats`, instead choosing to return its own row type. If we don't plan to use the new fields, maybe we should change the return type instead of adding the new fields?
Here's the documentation …
=> Update get_column_stats for Postgres 17

install/amazon_rds/04_configure_the_collector_docker.mdx, install/amazon_rds/04_configure_the_collector_ec2.mdx, install/amazon_rds/04_configure_the_collector_ecs.mdx, install/amazon_rds/04_configure_the_collector_eks.mdx, log-insights/setup/heroku-postgres/toc.yml
Maybe it's only me with my weird reading, but when you say "If you have multiple readers you want to monitor, do X", I feel like "well I don't need to monitor them all, let me skip reading/doing X" even though I have multiple readers with a cluster.
Actually, I was always wondering what these sentences actually means, and I didn't fully understand this until today. So I think it's the best to remove any ambiguity and clarify that monitoring them individually is necessary (IOW, using  for Aurora cluster with multiple readers.
Actually, just noticed that EC2 doc does say "this is only supported in two-node clusters (i.e. single reader instance)" for `cluster-ro` way, which is really clear. We could adopt this to other docs too 🤔
=> Clarify how to monitor Aurora cluster with multiple readers

collector/settings.mdx
The cluster / instance ID settings are generally required, not just
required for Log Insights.
=> Fix Google Cloud settings labeling

install/amazon_rds/04_configure_the_collector_eks.mdx
`helm show values pganalyze/pganalyze-collector` will fail with "repo pganalyze not found" if `helm repo add pganalyze https://charts.pganalyze.com/` hasn't run already.
Make sure to add that to the step before running `helm show values`.
=> Add a pganalyze repo first before helm show values

api/index.mdx, install/amazon_rds/_03_setup_iam_policy.mdx, log-insights/setup/amazon-rds/01_test_log_download.mdx
These two docs can be rendered within the app, and without the absolute path, the link will be broken (or rather, page won't be loaded).
Update the link to the full path so that it can be opened as a docs page in the separate window when accessed from the app.
=> Update IAM policy link to access from the app

install/amazon_rds/_04_setting_env_vars_single_ecs.mdx
As noted by a user:
- the trailing comma isn't valid in JSON
- `user` must be a string, but it's not a required field so I've removed it
=> ECS task JSON fixes

query-tuning/index.mdx
Missed this in the review, but this link is broken.
=> Update a broken link of collector workflow docs

components/CheckDocumentation/connections/ActiveQuery.tsx
In passing, also simplify the wording: with Heroku decreasing in popularity I don't think we need to call it out, and there's no need to take up space listing two possible formats the `pganalyze:no-alert` comment can be.
=> Add pg_repack to Active Query check documentation

explain/plan-comparison.mdx
- finish the parenthetical note for Buffers requirements
- show "EXPLAIN ANALYZE" as inline code block for consistency
=> Minor EXPLAIN Comparison docs fixes

install/troubleshooting/collector_crash.mdx
We missed updating this when we changed this in the systemd unit file shipped with the collector packages (in collector 0.62.0 / Nov 2024).
Unfortunately it appears that overriding MemoryLimit does not affect MemoryMax if it is set - the lower MemoryMax limit keeps being in effect.
=> Collector crash guidance: Document MemoryMax instead of MemoryLimit

components/helperSQL.ts
The backslashes in the regexp we use must be escaped for JavaScript.
=> Fix query tuning helper

log-insights/setup/self-managed/01_determine_log_location.mdx
When embedded in the app, these links previously redirected to the wrong domain (https://app.pganalyze.com/docs/...). Here, we fix the link target.
=> Fix external links in embedded log insights page

log-insights/setup/self-managed/02_configure_collector.mdx
Reported by the customer - we're using `=` elsewhere and also `=` is a standard format of INI config files, so let's update here.
=> Update the separator from : to =

_install_choice.mdx, install/azure_database/01_configure_azure_instance.mdx, install/toc.yml
As discussed internally, remove this from the officially supported list. I still kept some special tweaks note for Cosmos DB in the installation guide docs, but I added some caution in the beginning of the guide.
=> Remove Cosmos DB from the title, add note about Cosmos DB

components/CheckDocumentation/vacuum/XminHorizon.tsx
```
Xmin horizon check: Show TXID with separate epoch, and assigned at time
Since the statistics views in Postgres utilize the 32-bit version of
transaction IDs, but we track 64-bit internally, it can be confusing
to show the raw 64-bit value (since you can't visually compare it to
queries you run on the database). To improve, instead format it with
a separate epoch, separated by a colon, like we do for freezing stats.
Additionally show the specific assigned at timestamp inline, to help
identify the problem origin better, e.g. to use for comparison with
xact_start in pg_stat_activity, when xmin horizon is held back by a
long-running transaction.
In passing introduce a component to handle xmin information consistently,
and fix typing for "heldBackInfo", which was incorrectly marked as a …
```
=> Improve Xmin horizon check details

install/crunchy_bridge/01_deploy_the_collector.mdx, log-insights/setup/crunchy-bridge/01_create_helper_function_and_test.mdx
Using https://docs.crunchybridge.com/container-apps/pganalyze-quickstart as a reference.
Currently, Log Insights is unable to set up unless the user follows above. Two main things:
* They need to specify `log_destination` setting in the config
* `--privileged` needs to be added to the podman command
I also updated the test output log part a bit, and mention that the user can do `\t \a` to get better logs (otherwise, they get pretty terribly formatted logs like `\x1B[92m✓\x1B[0m Database connection:   ok\r`).
=> Update Crunchy Bridge instruction to support new logging

explain/scan-nodes/function-scan.mdx
Missed in aa025a5e6006b944699046d09a37105d7807b067. That commit added
some fields to the list, but did not add them to the frontmatter
metadata that is used to show this field data in some EXPLAIN views.
=> Add Important Fields to Function Scan node

opentelemetry/honeycomb.mdx
Honeycomb introduced a new type of API key called ingest keys, and it is recommended to use that over the configuration keys (the classic one) with Send Events permission. Update docs to reflect this. https://www.honeycomb.io/blog/ingest-only-api-keys
=> Use ingest key instead of Send Event permission key

install/amazon_rds/00_overview.mdx
I noticed a few typos while reading the docs, figured it would be nice to address them since they are public.
=> Fix typos in Amazon RDS install overview

api/queries/getIssues.mdx
This field has long been deprecated, and was recently removed from the API.
=> Remove secondary URL from getIssues documentation

api/queries/getQueryStats.mdx
`getQueryStats` supports returning the full normalized query, but that wasn't in the public documentation. This change was prompted by a support request asking for a way to export the full query text.
=> Add normalized query to getQueryStats documentation

util/checks/index.ts
The upstream type marks the `referent` field as optional. This should
match.
=> Correct a TypeScript definition for Issue

components/CodeBlock.gatsby.tsx, components/CopyToClipboard/index.tsx, components/MonitoringUserSetupInstructions.tsx, components/style.module.scss, install/amazon_rds/01_configure_rds_instance.mdx
This is just an initial PR to add a copy button to code blocks throughout docs. The work appears to have been started at one point but not fully implemented. I originally had most of the current markdown code blocks converted until I realized that there is an issue with multi-line strings that I'm struggling to fix before applying more widely.
A few note:
- I chose to just update the existing `CodeBlock.gatsby.tsx` since it was already being referenced a few places rather than have multiple components.
- I also didn't use the existing `CopyCodeBlock` component because it was more simplistic without code formatting and currently not used anywhere
- I'll note the what the issue is in the two example modified files - one MDX file, one TSX file - separately, but in essense:
- In the MDX file, …
=> Add copy capability to CodeBlocks in docs

components/helperSQL.ts
This was intended to match https://github.com/pganalyze/collector/pull/700, but missed subsequent changes to the function definition based on review feedback by accident. This caused errors in cases where no params were passed to the function.
=> Query Tuning: Correct definition of explain_analyze helper

components/VerifyConnection.tsx
This change unblocks https://github.com/pganalyze/pganalyze/pull/5032.
When trying to update the pganalyze/pganalyze/docs submodule, the type checker found an error:
```
docs/components/VerifyConnection.tsx:6:74 - error TS6133: 'host' is declared but its value is never read.
6 export const VerifyConnection: React.FunctionComponent<{host:string}> = ({host}) => {
~~~~~~
Found 1 error in docs/components/VerifyConnection.tsx:6
```
The issue is in the template literal where `{host}` is treated as a literal string instead of being interpolated. This fix changes `{host}` to `${host}` to properly interpolate the prop value, which resolves the TypeScript error.
=> Interpolate host to fix TypeScript check

directory.json, workbooks/enabling_pg_hint_plan.mdx, workbooks/toc.yml
Putting under Query Tuning section for now, but not linking from anything at the moment. There are several places in the existing doc that could potentially link from.
Part of https://github.com/pganalyze/pganalyze/issues/5068
=> Add docs for how to enable pg_hint_plan

enterprise/troubleshooting.mdx, install/amazon_rds/01_configure_rds_instance.mdx, workbooks/collector-workflow.mdx
- Enterprise setup instructions on AWS for IAM authentication reference `--http-put-response-hop-limit` but only for one specific error message. Adding another potential error for easier resolution.
- Collector workflow doesn't account for the function being run with the `search_path` of the collector database role (typically `pganalyze`). Providing alternative solutions for setting the `search_path` correctly.
- The collector automatically takes `aurora_stat_plan` into account if `aurora_compute_plan_id` is set to on (defaults to off). Referencing in docs for easier setup.
=> Various updates from recent support requests
