pganalyze/pganalyze-docs

directory.json
install.md
install/troubleshooting.md
install/troubleshooting/rds_pg_stat_statements_shared_preload_libraries.md

now showing the shared preload libraries information

updated RDS instance docs

---

explain/other-nodes/bitmap-and.md
explain/other-nodes/bitmap-or.md

See https://github.com/pganalyze/pganalyze/pull/507 and https://github.com/pganalyze/pganalyze/issues/489

Update bitmap op docs

---

install/amazon_rds/04_install_collector.md

See https://github.com/pganalyze/pganalyze/issues/744

Reference Amazon Linux 2 instead of original

---

explain/index.md
explain/insights/index.md

* Add missing I/O Heavy insight in EXPLAIN overview
* Fix its/it's error in Inefficient Index description
* Drop Nodes noise word in I/O Heavy and Expensive insight blurbs

Minor doc fixes

---

collector/settings.md

See https://github.com/pganalyze/collector/pull/105

Document new collector settings

---

collector/settings.md

See https://github.com/pganalyze/collector/pull/117

Document skip_if_replica setting

---

install/amazon_rds/03_setup_iam_policy.md

This updates the public docs to match the in-app docs, and removes a set
of unnecessary EC2 permissions.

Update IAM policy to reflect reduced permissions required

---

collector/settings.mdx
components/CollectorSettings.tsx
directory.json
log-insights/setup/index.mdx
log-insights/setup/syslog-server.mdx

Not sure if an extra subsection makes sense here, but this is
definitely too much info to fit into the table and all of it is
useful. Thoughts?

Document db_log_syslog_server collector setting

---

components/CheckDocumentation/connections/ActiveQuery.tsx
components/CheckDocumentation/connections/IdleTransaction.tsx
components/CheckDocumentation/index.tsx
components/CheckDocumentation/queries/Slowness.tsx
components/CheckDocumentation/replication/FollowerMissing.tsx
components/CheckDocumentation/replication/HighLag.tsx
components/CheckDocumentation/schema/IndexInvalid.tsx
components/CheckDocumentation/schema/IndexUnused.tsx
components/CheckDocumentation/settings/EnableFeatures.tsx
components/CheckDocumentation/settings/Fsync.tsx
components/CheckDocumentation/settings/SharedBuffers.tsx
components/CheckDocumentation/settings/Stats.tsx
components/CheckDocumentation/settings/WorkMem.tsx
components/CheckDocumentation/system/StorageSpace.tsx
components/PGDocsLink/index.tsx
components/SQL/index.tsx
components/SQL/style.module.scss
components/SmartAnchor.tsx
components/WithIcons.tsx
util/checks/index.ts

This does not yet include public check documentation, but allows the
core of the documentation to be shared.

Move Check docs into docs repo

---

directory.json
explain/other-nodes/sort.mdx

This will have it show in the Explain Node Details panel.

Add Sort Key to EXPLAIN Sort nodes important fields

---

components/CheckDocumentation/replication/FollowerMissing.tsx
components/CheckDocumentation/settings/SharedBuffers.tsx
components/CheckDocumentation/settings/Stats.tsx
components/CheckDocumentation/settings/WorkMem.tsx
util/checks/index.ts

- Document severity of checks where this info was missing
- Make check severity info available programmatically

Update check documentation

---

checks/pagerduty.mdx
components/SmartAnchor.tsx
directory.json

Following the template provided at https://github.com/PagerDuty/app-documentation-templates/blob/master/integration-guide-template.md

Add PagerDuty integration docs

---

install/heroku_postgres/02_attach_databases.mdx
install/heroku_postgres/util.ts
log-insights/setup/heroku-postgres/01_add_log_drain.mdx
log-insights/setup/heroku-postgres/02_verify_log_drain.mdx
log-insights/setup/heroku-postgres/03_restart_collector.mdx

- Fix typo
- Shorten Heroku command output table columns
- Better handling of app and attachment names
- Use placeholder app names more consistently

Clarify Heroku setup instructions

---

components/CheckDocumentation/connections/ActiveQuery.tsx
components/CheckDocumentation/connections/IdleTransaction.tsx
components/CheckDocumentation/queries/Slowness.tsx
components/CheckDocumentation/schema/IndexInvalid.tsx
components/CheckDocumentation/schema/IndexUnused.tsx
components/SQL/index.tsx
components/SQL/style.module.scss
util/checks/index.ts

See https://github.com/pganalyze/pganalyze/pull/1481
(This should have been opened and merged before that--right now
that code relies on this branch.)

Update docs for issues with multiple references

---

api/queries/getQueryStats.mdx

https://pganalyze.zendesk.com/agent/tickets/2230

Update getQueryStats script to use HTTPS

---

directory.json
explain/setup/heroku/01_enable_log_explain.mdx
explain/setup/heroku/02_test_and_verify.mdx
explain/setup/index.mdx
explain/setup/log_explain/01_create_helper_functions.mdx
explain/setup/log_explain/index.mdx
log-insights/setup/heroku-postgres/02_verify_log_drain.mdx

- Fix minor typo
- Note that 'heroku logs -d router' may not immediately show output
- Add Heroku-specific EXPLAIN setup instructions

Improve Heroku onboarding docs

---

components/CheckDocumentation/index.tsx
components/CheckDocumentation/index_advisor/MissingIndex.tsx
util/checks/index.ts

Add Missing Index check metadata and initial docs

Add Missing Index Check metadata

---

directory.json
install/troubleshooting.mdx
install/troubleshooting/column_stats_helper.mdx

Add troubleshooting instructions for setting up column stats helper

---

directory.json
enterprise/index.mdx
enterprise/integrations.mdx

This is largely based on instructions I've been giving out in support
tickets when asked. It's a little vague, but we have not received any
negative feedback, so I think we can document this publicly and
improve it later.

Add initial Enterprise Slack / PagerDuty instructions

---

directory.json
explain/other-nodes/incremental-sort.mdx

This node is new in Postgres 13.

Add docs for the Incremental Sort EXPLAIN node type

---

indexing-engine/changelog.mdx
indexing-engine/limitations.mdx

- note initial PostGIS support
- note support for queries with table references in subqueries inside
casts

Update Indexing Engine changelog and limitations

---

components/CollectorLogTest.tsx
components/CollectorSettings.tsx
log-insights/setup/amazon-rds/01_test_log_download.mdx
log-insights/setup/azure-database/05_configure_collector.mdx
log-insights/setup/google-cloud-sql/04_configure_collector.mdx

```
Log Insights: Use consistent log test instructions for containers
This makes sure the log test instructions are aware of whether the
collector is configured from ENV variables (i.e. running as a container),
or in a virtual machine from a config file.
Additionally, this makes the instructions consistent across RDS/GCP/Azure
by using a component instead of copying the same text multiple times.
```
```
Log Insights for GCP: Use CollectorSettings component to show config
This ensures we are aware of whether the collector runs in a container,
and matches RDS and Azure.
In passing, fix a React key error in the CollectorSettings component.
```

Log Insights: Improve collector config/test instructions

---

components/CheckDocumentation/connections/BlockingQuery.tsx
components/CheckDocumentation/index.tsx
util/checks/index.ts

This PR adds the check documentation for the Blocking Query check.

Add Blocking Query check documentation

---

components/CheckDocumentation/connections/BlockingQuery.tsx

What title says. It'll be changed in the main app side, so let's change this in the docs too.

Update blocking query issue details key name for autovacuum wraparound

---

components/MonitoringUserSetupInstructions.tsx

These are no longer supported.

Drop documentation specific to Postgres 9.5 and older

---

collector/settings.mdx
install/amazon_rds/05_configure_the_collector_ec2.mdx

- disable_citus_schema_stats
- db_use_iam_auth
- new rds-ca-global option for db_sslrootcert

Document new and updated collector settings

---

enterprise/settings.mdx

This was introduced with enterprise-v2023.03.0 release.
Documenting here so that the Enterprise customers could take advantage of it potentially.

Add instruction for sidekiq prometheus monitoring

---

components/CheckDocumentation/vacuum/InsufficientVacuumFrequency.tsx
util/checks/index.ts

Sadly realized that having this in bytes is not a good idea.

Use notify_mb instead of notify_bytes

---

components/CheckDocumentation/vacuum/XminHorizon.tsx
util/checks/index.ts

Follow-up of https://github.com/pganalyze/pganalyze-docs/pull/154

Update the resolve condition of xmin horizon check

---

components/CheckDocumentation/index_advisor/MissingIndex.tsx
directory.json
index-advisor/checks-and-alerts.mdx
index-advisor/getting-started.mdx
index-advisor/index.mdx
index-advisor/reason-about-insights.mdx
index-advisor/test-insights.mdx
index-advisor/toc.yml
index.mdx
indexing-engine/index.mdx
indexing-engine/what-if-analysis.mdx

- Rename Index Advisor Opportunities to Insights
- Update directory.json

Rename Index Advisor Opportunities to Insights

---

index-advisor/reason-about-insights.mdx

Update additional mentions of Opportunities to Insights

---

components/CheckDocumentation/index.tsx
components/CheckDocumentation/vacuum/MxidWraparound.tsx
components/CheckDocumentation/vacuum/TxidWraparound.tsx
util/checks/index.ts

Two checks are really similar, but slightly different.

Add VACUUM: Freezing - Approaching Transaction/Multixact ID Wraparound check doc

---

checks/toc.yml
util/checks/index.ts

In addition to TOC update, I also updated the check name to use "of" and "by" in non-title case

Update TOC for checks doc

---

api/mutations/deleteServer.mdx
api/mutations/index.mdx
api/mutations/toc.yml
api/mutations/updateServer.mdx
directory.json

We've recently added additional AWS options to addServer, so document them. Additionally document the updateServer and deleteServer actions, to allow better automation of which servers are registered in pganalyze.

API docs: Update addServer, add updateServer and deleteServer

---

accounts/billing.mdx
accounts/toc.yml
directory.json

This also serves as a location we can link to to explain the upcoming "billable server" terminology.

Add billing FAQ to explain a few common questions about billing

---

collector/index.mdx

Preview: https://pganalyze-we-collector--kdqcvc.herokuapp.com/docs/collector#data-collection-and-snapshot-frequency
I'll likely need to get eyes from someone who is familiar with the collector to make sure I'm writing the correct information.
@jensy Maybe you could review regarding if it's a good structure?

Create section for collector Data collection and Snapshot submission Frequency

---

collector/settings.mdx

Part of https://github.com/pganalyze/collector/pull/465

Add otel_service_name description

---

collector/index.mdx
components/CollectorLogTest.tsx
install/amazon_rds/05_configure_the_collector_ecs.mdx
log-insights/setup/heroku-postgres/03_restart_collector.mdx

See https://github.com/pganalyze/collector/pull/482

Update docs for updated collector output

---

install/troubleshooting/collector_crash.mdx

Update example log line for new collector output format

---

collector/settings.mdx
log-insights/setup/azure-database/05_configure_collector.mdx
log-insights/setup/azure-database/troubleshooting.mdx

Pairing PR of https://github.com/pganalyze/collector/pull/486
Technically blocked by that PR, but given that it's actually not working currently, I think it's safe to ship this independently too.
With above collector change, following the documentation should complete the setup without a problem. However, there is a caveat when multiple identities are assigned to the VM, so let's clarify what needs to be done in that case.

Clarify how to specify the managed identity when multiple

---

api/mutations/addServer.mdx
api/mutations/updateServer.mdx
components/MonitoringUserSetupInstructions.tsx
directory.json
enterprise/log-insights.mdx
enterprise/releases/2022-08-0.mdx
install/troubleshooting.mdx
install/troubleshooting/pg_read_file_helper.mdx
install/troubleshooting/toc.yml

- Add pg_read_file troubleshooting docs
- Drop get_stat_replication docs

Migrate collector README items to docs

---

components/MonitoringUserSetupInstructions.tsx

See https://github.com/pganalyze/collector/pull/550

Update helper function definitions to work around RDS issue

---

collector/toc.yml
collector/uninstalling.mdx
directory.json

It's super simple one, but good enough as a starter

Add a simple collector uninstalling step docs

---

collector/settings.mdx

For https://github.com/pganalyze/collector/pull/556

Enable log filtering by default

---

collector/settings.mdx
directory.json
log-insights/setup/index.mdx
log-insights/setup/opentelemetry.mdx
log-insights/setup/self-managed/01_determine_log_location.mdx
log-insights/setup/toc.yml

Pairing PR of https://github.com/pganalyze/collector/pull/544

Add docs for k8s + otel log insight setup

---

components/CollectorPkgInstallInstructions.tsx

Pairing PR of https://github.com/pganalyze/collector/pull/569

Avoid using apt-key command for the collector installation for Debian

---

collector/settings.mdx

See https://github.com/pganalyze/collector/pull/562

Update docs for disable_citus_schema_stats

---

components/CheckDocumentation/schema/IndexUnused.tsx

Include expression indexes in Index Unused check

---

accounts/sso/index.mdx

As pointed out by a prospective customer, this is not a limitation during Enterprise Server trials.

SSO: Clarify that its not available for cloud-based trials

---

log-insights/limits.mdx

This doc updated was missed in https://github.com/pganalyze/collector/pull/301

Fix Log Insights limits settings docs

---

query-performance/index.mdx

Some of them are outdated now + with the Aurora plan stats, we want to update this part of docs.

Update EXPLAIN Plans description

---

install/amazon_rds/04_configure_the_collector_docker.mdx
install/amazon_rds/04_configure_the_collector_ec2.mdx
install/amazon_rds/04_configure_the_collector_ecs.mdx
install/amazon_rds/04_configure_the_collector_eks.mdx

Follow-up from https://github.com/pganalyze/pganalyze-docs/pull/284#discussion_r1857527370

Rephrase a cluster with multiple readers

---

accounts/permissions.mdx
enterprise/settings.mdx

For a new permission - don't need to merge yet but creating a PR before forget.

Add Tune Queries as an option of DEFAULT_ORG_ROLE

---

install/amazon_rds/04_configure_the_collector_ecs.mdx
install/amazon_rds/04_configure_the_collector_eks.mdx

We don't show how to run the test command with EKS setup well, so let's add it.
I've added ECS too. Haven't tested with ECS but it should... work?

Add description of how to run the test with EKS and ECS

---

collector/pii-filtering.mdx
collector/settings.mdx
collector/toc.yml
directory.json
pii-filtering/index.mdx

Maybe this should be broken out to a separate section? It would
probably also be useful to note what parts of the application are
impacted, but I left that as a follow-up step (possibly still in this
patch).

Flesh out PII filtering docs

---

collector/settings.mdx

Fix PII filtering link

---

collector/settings.mdx

- Clarify automatic collector reload behavior
- Drop commented-out PGA_ENABLE_REPORTS section
- Collector settings cleanup (see details in commit message)

Polish collector settings docs

---

directory.json
log-insights/setup/crunchy-bridge/01_create_helper_function_and_test.mdx

Got feedback that it would be nice to restate in this section too. As it won't hurt adding it, I simply added the line.

Add grant statement in Log Insights docs too

---

components/helperSQL.ts

Pairing PR of https://github.com/pganalyze/collector/pull/700

Update pganalyze.explain_analyze helper function definition

---

util/checks/index.ts

Adding this ahead of the release so early access code works as expected.

Add upcoming Query Tuning check with daily frequency

---

checks/toc.yml

Not a bit deal so it can go with any of the future changes (aka I think we don't need to deploy web for this one)

Fix Advisor Insight to Advisor Insights
